---
# Read the Docs configuration file. For more information see official
# documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: ./requirements.txt
